### PR TITLE
Adds script to run tests on specified files.

### PR DESCRIPTION
**Pull request by dberenba**

### CODE REVIEW

**Comment by JohnUrban** [comment]
Thanks! The test script looks ready to go, and I'd be happy to merge it to be able to test files again.

As for the import statements, I had already fixed them to be:

```
from fast5tools.f5class import *
```

and I modified the for-loops in the script bodies to be:

```
for f5 in Fast5List:
  #do stuff
```

So the import statements you changed them to (`from fast5tools import f5class`) will break the scripts again unless I change the bodies to:

```
for f5 in f5class.Fast5List:
  ##dostuff
```

My preference is to use `from fast5tools.f5class import *` in this particular case. I do not expect name clashes without the dot notation, and it is less busy-looking in my opinion to just use `for f5 in Fast5List`.

Is there a way to partially merge?

**Comment by JohnUrban** [comment]
I will try cherry picking:
http://stackoverflow.com/questions/7217031/github-accept-pull-request-but-only-some-commits

Thanks for itemizing the commits so well. This should be simple.

**Comment by dberenba** [comment]
Yeah, I changed the import statements before I pulled your changes, but I think I reversed it and kept your version of the import statements once I saw what you did. The only changes that would be merged are the ones you can see under the "Files changed" tab, so I think you should be safe to merge. Take a look and let me know if you still have questions.

**Comment by dberenba** [comment]
I don't think you should need to cherry pick here. I already reverted my import statement changes when I resolved the merge conflict.

**Comment by JohnUrban** [comment]
You are absolutely right. I will just merge. If it makes the other changes, they would be trivial to fix anyway.

**Comment by dberenba** [comment]
Thanks, John! Sorry if I slowed down your productivity today!

**Comment by JohnUrban** [comment]
No worries. It is all looking good. Enjoy your 4th of July festivities.

**Pull request merged**
